name: pipeline

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip install -e ./[testing]

      - name: Install pypa/build
        run: |
          python -m pip install build --user

      - name: Build binary wheel and source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/ .

      - name: Test Wheel install and import
        run: |
          python -c "import cadet; print(cadet.__version__)"

      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests --rootdir=tests
